apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: storestoretessera
  namespace: store-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: storestoretessera
  chart:
    git: ssh://git@github.com/Pramod-Somanchi/blockchain-automation-framework.git
    ref: develop
    path: platforms/quorum/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: store-quo
      labels:
    images:
      node: quorumengineering/quorum:2.5.0
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:0.11
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: store
      status: default
      consensus: raft
      subject: O=Store,OU=Store,L=40.73/-74/New York,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: true/false
      ports:
        rpc: 8546
        raft: 50401
        tm: 8443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://ac5ee81c5ca6211ea9af20220d9b0e54-1122465898.ca-central-1.elb.amazonaws.com:9000/
      secretprefix: secret/store-quo/crypto/store
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumstore
    tessera:
      dburl: "jdbc:mysql://store:3306/demodb"
      dbusername: demouser
      url: "https://store.dlt.clusterg303.aws.bafevent.com:8443"
      othernodes:
        - url: https://carrier.carrier.dlt.clusterg303.aws.bafevent.com:8443
        - url: https://manufacturer.manufacturer.dlt.clusterg303.aws.bafevent.com:8443
        - url: https://store.store.dlt.clusterg303.aws.bafevent.com:8443
        - url: https://warehouse.warehouse.dlt.clusterg303.aws.bafevent.com:8443
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImFsbG9jIjogewogICAgICAgICIzYjI4YjY1YmQ4YzVmNTc2Y2VmMjQzNmU3NTYzYjA2MjdjNzExMDUxIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgImJkODBlNWU3ZTBkNWI4NWYyMTZiNzE1NDk3Y2IwNGQ4MjIxY2I5ZTYiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfSwKICAgICAgICAiZDk2Y2NlNDNmYWU0MTBlMDgwYjE4ZmRkZmQyMzBkYThiMzRkYjc0ZCI6IHsKICAgICAgICAgICAgImJhbGFuY2UiOiAiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgICAgICB9LAogICAgICAgICJlNTBjNTljODFjNjg4YmIzMTlkNmIzNGY0YzgzMTI2YzE0ZDdhYTcxIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0KICAgIH0sCiAgICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICJjb25maWciOiB7CiAgICAgICAgImJ5emFudGl1bUJsb2NrIjogMSwKICAgICAgICAiY2hhaW5JZCI6IDEwLAogICAgICAgICJjb25zdGFudGlub3BsZUJsb2NrIjogMCwKICAgICAgICAiZWlwMTUwQmxvY2siOiAxLAogICAgICAgICJlaXAxNTBIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAgICAgImVpcDE1NUJsb2NrIjogMCwKICAgICAgICAiZWlwMTU4QmxvY2siOiAxLAogICAgICAgICJpc1F1b3J1bSI6IHRydWUsCiAgICAgICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAgICAgInJhZnRTZWNvbmRzIjogdHJ1ZSwKICAgICAgICAidHhuU2l6ZUxpbWl0IjogMTI4CiAgICB9LAogICAgImRpZmZpY3VsdHkiOiAiMHgwIiwKICAgICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICJnYXNMaW1pdCI6ICIweEUwMDAwMDAwMDAiLAogICAgIm1peGhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDY0NzU3MjYxNmM2NTc4NzM2NTY0NmM2NTc4IiwKICAgICJub25jZSI6ICIweDAiLAogICAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICJ0aW1lc3RhbXAiOiAiMHgwMCIKfQ==
    staticnodes: 
      [
    "enode://fe5a4157f58d326e481b9646425a8447018962b4026516eae75ba328241c8f3097a70e19c6c238362f2a78e7800af83a8e8bb4ddeb1a6c1f17e97d3385730bf1@carrier.dlt.clusterg303.aws.bafevent.com:15010?discport=0&raftport=15013",
    "enode://d62c0ddfe7dcb09ab39583cf500a6390825bf0aa23ec791c6f7da158001d50d68d27cffdfb70ee0df9f7403224ffde5465181750b8244e9a9fc676934aa22b7e@manufacturer.dlt.clusterg303.aws.bafevent.com:15020?discport=0&raftport=15023",
    "enode://d712499241505767863826182f0b8d8f7bd7e6dd35144bdbffabc5dd22f93c2242ae042ac6e570ccde859987a081483ce9ba07f8942713f68e203b1618b97e28@store.dlt.clusterg303.aws.bafevent.com:15030?discport=0&raftport=15033",
    "enode://7c80cba417206a71d2ce4128f28f78de6ca927c534e6c6471823f6ed1762252c06fa1972233ddcdc06cfe6d9d521a47a40de79d3b72fada0120b8f1c3bde11f9@warehouse.dlt.clusterg303.aws.bafevent.com:15040?discport=0&raftport=15043"
]
    proxy:
      provider: "ambassador"
      external_url: store.dlt.clusterg303.aws.bafevent.com
      portTM: 8443
      rpcport: 15031
      quorumport: 15030
  
      portRaft: 15033
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
